# -*- coding: utf-8 -*-
"""EXCEPTION-HANDLING & DEBUGGING TECHNIQUES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqZgY0bRorE2WIS7Ie8fpemOvPOOr0LF
"""

# ============================================================
#    EXCEPTION HANDLING & DEBUGGING - COMPLETE ASSIGNMENT
# ============================================================


# ============================================================
# SECTION A: EXCEPTION HANDLING
# ============================================================

print("=" * 60)
print("         SECTION A: EXCEPTION HANDLING")
print("=" * 60)

# -----------------------------------------------------------
# A.Q1 - What is an exception in Python?
# -----------------------------------------------------------
print("\n--- A.Q1: What is an Exception? ---")
print("""
An exception is an error that occurs during the execution of
a program. It stops the normal flow of the program.

Unlike syntax errors (which are caught before running),
exceptions happen at runtime - while the program is running.

Python has many built-in exceptions like:
  - ZeroDivisionError
  - ValueError
  - FileNotFoundError
  - TypeError
  - IndexError
""")

# -----------------------------------------------------------
# A.Q2 - Two real-life examples
# -----------------------------------------------------------
print("\n--- A.Q2: Two Real-Life Examples ---")
print("""
Example 1 - ATM Machine:
  You enter the wrong PIN 3 times.
  The machine raises an exception (blocks your card).
  Without exception handling, the ATM would crash.

Example 2 - Calculator App:
  User tries to divide a number by zero.
  Mathematically impossible, so a ZeroDivisionError occurs.
  The app shows "Cannot divide by zero" instead of crashing.
""")

# -----------------------------------------------------------
# A.Q3 - Handle ZeroDivisionError
# -----------------------------------------------------------
print("\n--- A.Q3: ZeroDivisionError Handling ---")

num1 = 10
num2 = 0  # This will cause ZeroDivisionError

try:
    result = num1 / num2
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

# Also show a successful case
print("\nSuccessful division:")
try:
    result = 10 / 2
    print("10 / 2 =", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")

# -----------------------------------------------------------
# A.Q4 - Handle ValueError with user input
# -----------------------------------------------------------
print("\n--- A.Q4: ValueError Handling ---")

# Simulating user input (in real program use input())
user_input = "abc"  # invalid - not a number
print(f"User entered: '{user_input}'")

try:
    number = int(user_input)
    print("You entered:", number)
except ValueError:
    print("Error: Invalid input! Please enter a valid number.")

# Show valid input case
print("\nWith valid input:")
user_input2 = "25"
print(f"User entered: '{user_input2}'")
try:
    number = int(user_input2)
    print("You entered:", number)
except ValueError:
    print("Error: Invalid input!")

# -----------------------------------------------------------
# A.Q5 & Q6 - Open file and handle FileNotFoundError
# -----------------------------------------------------------
print("\n--- A.Q5 & Q6: FileNotFoundError Handling ---")

try:
    f = open("data.txt", "r")
    content = f.read()
    print("File contents:", content)
    f.close()
except FileNotFoundError:
    print("Error: File 'data.txt' does not exist!")

# Create the file and try again
with open("data.txt", "w") as f:
    f.write("Hello from data.txt!")

print("\nAfter creating the file:")
try:
    f = open("data.txt", "r")
    content = f.read()
    print("File contents:", content)
    f.close()
except FileNotFoundError:
    print("Error: File does not exist!")

# -----------------------------------------------------------
# A.Q7 - try-except-else to add two numbers
# -----------------------------------------------------------
print("\n--- A.Q7: try-except-else Example ---")

# Simulating valid input
a = "15"
b = "25"
print(f"User entered: {a} and {b}")

try:
    num1 = int(a)
    num2 = int(b)
except ValueError:
    print("Error: Please enter valid numbers!")
else:
    # else block runs only if NO exception occurred
    result = num1 + num2
    print("Sum =", result)
    print("(else block ran because no error occurred)")

# Simulating invalid input
print("\nWith invalid input:")
a = "10"
b = "xyz"
print(f"User entered: {a} and {b}")

try:
    num1 = int(a)
    num2 = int(b)
except ValueError:
    print("Error: Please enter valid numbers!")
else:
    result = num1 + num2
    print("Sum =", result)

# -----------------------------------------------------------
# A.Q8 - finally block demonstration
# -----------------------------------------------------------
print("\n--- A.Q8: finally Block Demonstration ---")

print("Case 1 - Division by zero:")
try:
    result = 10 / 0
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")
finally:
    print("Program finished.")

print("\nCase 2 - Successful division:")
try:
    result = 10 / 2
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")
finally:
    print("Program finished.")

print("""
NOTE: The 'finally' block ALWAYS runs,
whether an exception occurred or not.
""")


# ============================================================
# SECTION B: DEBUGGING TECHNIQUES
# ============================================================

print("=" * 60)
print("         SECTION B: DEBUGGING TECHNIQUES")
print("=" * 60)

# -----------------------------------------------------------
# B.Q1 - What is debugging?
# -----------------------------------------------------------
print("\n--- B.Q1: What is Debugging? ---")
print("""
Debugging is the process of finding and fixing errors (bugs)
in a program so that it runs correctly.

The word 'bug' comes from 1947 when a real moth was found
stuck inside a computer causing it to malfunction.

Debugging involves:
  - Finding where the error is
  - Understanding why it happens
  - Fixing the error
  - Testing to make sure it is fixed
""")

# -----------------------------------------------------------
# B.Q2 - Why is debugging important?
# -----------------------------------------------------------
print("\n--- B.Q2: Why is Debugging Important? ---")
print("""
1. Finds errors before they cause bigger problems
2. Makes programs run correctly and efficiently
3. Helps programmers understand their own code better
4. Prevents crashes in real-world applications
5. Saves time in the long run - small bugs found early
   are easier to fix than big bugs found late
""")

# -----------------------------------------------------------
# B.Q3 - Three types of errors with 5 examples each
# -----------------------------------------------------------
print("\n--- B.Q3: Three Types of Errors ---")

print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TYPE 1: SYNTAX ERROR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
A syntax error occurs when Python cannot understand the
code because of wrong grammar or spelling mistakes.
These are caught BEFORE the program runs.

Example 1 - Missing colon:
  if x > 5       ← should be: if x > 5:
      print("hi")

Example 2 - Missing closing bracket:
  print("Hello"  ← should be: print("Hello")

Example 3 - Wrong indentation:
  def greet():
  print("Hi")    ← should be indented inside function

Example 4 - Misspelled keyword:
  whille True:   ← should be: while True:

Example 5 - Missing quotes:
  name = John    ← should be: name = "John"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TYPE 2: RUNTIME ERROR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
A runtime error occurs WHILE the program is running.
The code looks correct but fails during execution.

Example 1 - ZeroDivisionError:
  x = 10 / 0    ← cannot divide by zero

Example 2 - FileNotFoundError:
  open("ghost.txt", "r")  ← file does not exist

Example 3 - ValueError:
  int("hello")  ← cannot convert text to integer

Example 4 - IndexError:
  my_list = [1, 2, 3]
  print(my_list[10])  ← index 10 does not exist

Example 5 - NameError:
  print(age)    ← variable 'age' was never defined

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TYPE 3: LOGICAL ERROR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
A logical error means the program runs without crashing
but gives WRONG results. No error message is shown.
These are the hardest to find!

Example 1 - Wrong operator:
  area = length + width   ← should be: length * width

Example 2 - Wrong condition:
  if age > 18:            ← should be: if age >= 18:
      print("Adult")      ← misses people exactly 18

Example 3 - Off by one error:
  for i in range(1, 10):  ← misses 10, should be range(1, 11)

Example 4 - Wrong average formula:
  avg = a + b / 2         ← should be: avg = (a + b) / 2

Example 5 - Subtraction instead of addition:
  total = price - tax     ← should be: total = price + tax
""")

# -----------------------------------------------------------
# B.Q4 - Identify error in: print(10 / 0)
# -----------------------------------------------------------
print("\n--- B.Q4: Identify the Error ---")
print("""
Code: print(10 / 0)

Error Type: RUNTIME ERROR (ZeroDivisionError)

Why it occurs:
  - The syntax is correct (Python can read it)
  - But during execution, Python tries to divide 10 by 0
  - Division by zero is mathematically impossible
  - So Python raises a ZeroDivisionError at runtime

Error message you would see:
  ZeroDivisionError: division by zero
""")

# Demonstrate the error being caught
print("Demonstration:")
try:
    print(10 / 0)
except ZeroDivisionError as e:
    print("Caught Error:", e)

# -----------------------------------------------------------
# B.Q5 - Print debugging
# -----------------------------------------------------------
print("\n--- B.Q5: Print Debugging ---")

# Simulating user input
user_input = "42"
print(f"[DEBUG] Raw input received: '{user_input}'")

try:
    number = int(user_input)
    print(f"[DEBUG] After int() conversion: {number}")
    print(f"[DEBUG] Type of variable: {type(number)}")

    result = number * 2
    print(f"[DEBUG] After multiplying by 2: {result}")

    print(f"\nFinal Result: {result}")

except ValueError:
    print("[DEBUG] ERROR: Could not convert input to integer!")

print("""
NOTE: Print debugging means adding print() statements
at different points to check what value a variable holds.
This helps find where the bug is.
""")

# -----------------------------------------------------------
# B.Q6 - Read error message for x = int("abc")
# -----------------------------------------------------------
print("\n--- B.Q6: Read the Error Message ---")
print("""
Code: x = int("abc")

Error Type: RUNTIME ERROR (ValueError)

Explanation:
  - int() tries to convert the string "abc" into an integer
  - "abc" contains letters, not digits
  - Python cannot convert letters to a number
  - So it raises a ValueError

Error message you would see:
  ValueError: invalid literal for int() with base 10: 'abc'

What it means:
  - 'invalid literal' = the value given is not valid
  - 'for int() with base 10' = we are using decimal numbers
  - "'abc'" = this is the value that caused the problem
""")

# Demonstrate
print("Demonstration:")
try:
    x = int("abc")
except ValueError as e:
    print("Caught Error:", e)

# -----------------------------------------------------------
# B.Q7 - Handle both ValueError and ZeroDivisionError
# -----------------------------------------------------------
print("\n--- B.Q7: Handle ValueError and ZeroDivisionError ---")

def safe_divide(a_str, b_str):
    try:
        a = int(a_str)
        b = int(b_str)
        result = a / b
        print(f"Result: {a} / {b} = {result}")

    except ValueError:
        print("Error: Invalid input! Please enter numbers only.")

    except ZeroDivisionError:
        print("Error: Cannot divide by zero!")

# Test Case 1 - Invalid input
print("Test 1 - Invalid input ('abc', '5'):")
safe_divide("abc", "5")

# Test Case 2 - Division by zero
print("\nTest 2 - Division by zero ('10', '0'):")
safe_divide("10", "0")

# Test Case 3 - Successful division
print("\nTest 3 - Valid input ('20', '4'):")
safe_divide("20", "4")


print("\n" + "=" * 60)
print("           ASSIGNMENT COMPLETE!")
print("=" * 60)